#!/bin/bash

if [ -z "$INVDIR" ]; then
    invdir=~/.inventory
else
    invdir="$INVDIR"
fi

if [ ! -d "$invdir" ]; then
	echo ""$invdir" does not exist, creating..."
    mkdir "$invdir"
fi

inv_file="$1"

if [ -z "$inv_file" ]; then
    inv_file="$(gum file -a $INVDIR)"
    inv_file="$(basename $inv_file)"
fi

if [ ! -e "$invdir"/"$inv_file" ]; then
    echo "You can't drop something that doesn't exist!"
else
    if [ -e ./"$inv_file" ]; then
        printf "Oh no!\nThe file that you are trying to drop already exists. Please rename it or drop it somewhere else.\n"
    else
        mv "$invdir"/"$inv_file" ./
        echo "You dropped "$inv_file"."
    fi
fi

files=(""$invdir"/*")
filesnum=$(ls -l "$invdir" | grep -v ^t | wc -l)

if [ "$filesnum" -eq 0 ]; then
    echo "Your inventory is empty."
else
    echo "Your inventory now contains:"
    for i in ${files[@]}; do
        echo "${i##*/}"
    done
fi
