#!/usr/bin/env bun
/// <reference path="/g/ts-defs/jsh.d.ts" />
/// <reference path="/g/ts-defs/meow.d.ts" />
/// <reference path="/g/ts-defs/chalk.d.ts" />
/// https://github.com/bradymholt/jsh
/// https://github.com/sindresorhus/meow
/// https://github.com/klaudiosinani/qoa
/// https://github.com/chalk/chalk

import "jsh";
import qoa from "qoa";
import meow from "meow";
import chalk from "chalk";

let paclines = $("yay -Qqt").split("\n");

async function test() {}

await test();

for (let i = 0; i < paclines.length; ++i) {
    let line = paclines[i];
    let info = $("yay -Qi " + line).split("\n");
    for (let j = 0; j < info.length; ++j) {
        if (info[j].startsWith("Name")) {
            echo(info[j].split(": ")[1]);
        }
        if (info[j].startsWith("Description")) {
            echo("    \x1b[2m" + info[j].split(": ")[1] + "\x1b[0m");
        }
    }
    echo("");
}

