#!/usr/bin/env bash

function execute() {
    clear
    echo "$@"
    eval "$@"
}

pwd

execute "$@"

inotifywait --quiet --recursive --monitor --event modify --format "%w%f" . \
| while read change; do
    execute "$@"
done
