#!/bin/bash

V_DIR_MUSIC="$HOME/documents/music/ytermusic"
V_DIR_CACHE="$HOME/.cache/ytermusic"

die() {
    echo "Error: $@"; exit 1
}

[ -d "$V_DIR_MUSIC" ] || die "ytermusic backup dir not found"
[ -d "$V_DIR_CACHE" ] || mkdir -p "$V_DIR_CACHE"

# -a = recursive + preserve
# -u = update, copies only newer
# -v = verbose
rsync -auv --progress $V_DIR_MUSIC/ $V_DIR_CACHE

