export XDG_DATA_HOME=$HOME/.local/share
export XDG_CONFIG_HOME=$HOME/.config
export XDG_STATE_HOME=$HOME/.local/state
export XDG_DATA_DIRS=$HOME/.local/share:/usr/local/share:/usr/share
export XDG_CONFIG_DIRS=$HOME/.config:/etc/xdg
export XDG_CACHE_HOME=$HOME/.cache
export XDG_RUNTIME_DIR=/run/user/$(id -u)

export ZDOTDIR=$XDG_CONFIG_HOME/zsh

