# Autogenerated config.py
import os

config_home = os.environ["XDG_CONFIG_HOME"] if "XDG_CONFIG_HOME" in os.environ else os.path.expanduser("~/.config")

try:
    config = config
    c = c
except NameError:
    pass

config.load_autoconfig(True)

# ~/.local/share/qutebrowser

c.aliases = {
    'w': 'session-save',
    'q': 'close',
    'qa': 'quit',
    'wq': 'quit --save',
    'wqa': 'quit --save',
    'o': 'open',
    'yt': 'open https://youtube.com/',
    'gh': 'open https://github.com/',
    'gl': 'open https://gitlab.com/',
    'tg': 'open https://web.telegram.org/k/',
    's': 'open',
    'g': 'open',
    'rund': 'open http://run.dlang.io/',
    'discord': 'open https://discord.com/channels/@me',
    'ym': 'open https://music.yandex.ru/home',
    'mk': 'open https://market.yandex.ru',
    'bashfmt': 'open https://misc.flogisoft.com/bash/tip_colors_and_formatting',
}

c.url.default_page = 'https://home.sily.dev/'
c.url.open_base_url = True

eng_google = 'https://google.com/search?q={}&udm=14'
eng_duck = 'https://duckduckgo.com/?q={}'
eng_phind = 'https://phind.com/search?q={}'
eng_metager = 'https://metager.org/?q={}'
eng_dub = 'https://code.dlang.org/search?q={}'
eng_arch = 'https://wiki.archlinux.org/index.php?search={}'
eng_git = 'https://github.com/search?q={}'
eng_repo = 'https://github.com/{}'
eng_srht = 'https://git.sr.ht/~{}'
eng_yt = 'https://www.youtube.com/results?search_query={}'
eng_music = 'https://music.yandex.ru/home?null={}'
eng_dlang = 'https://google.com/search?domains=dlang.org&q={}+site:dlang.org/phobos&udm=14'
eng_mk = 'https://market.yandex.ru/?q={}'
eng_surf = 'https://surf.sily.dev/?q={}'

c.url.searchengines = {
    'DEFAULT': eng_surf,
    'd': eng_duck,
    's': eng_surf,
    'p': eng_phind,
    'g': eng_google,
    'm': eng_metager,
    'dl': eng_dlang,
    'D': eng_dub,
    'a': eng_arch,
    'gh': eng_git,
    'repo': eng_repo,
    'hut': eng_srht,
    'y': eng_yt,
    'yt': eng_yt,
    'ym': eng_music,
    'mk': eng_mk,
}

c.url.start_pages = [ c.url.default_page ]


c.auto_save.interval = 15000
c.auto_save.session = True

c.backend = 'webengine'

c.changelog_after_upgrade = 'minor'

# Background color for webpages if unset (or empty to use the theme's color).
# c.colors.webpage.bg = BG

# c.colors.webpage.darkmode.algorithm = 'lightness-cielab'
c.colors.webpage.darkmode.enabled = False
# c.colors.webpage.darkmode.grayscale.all = False
# c.colors.webpage.darkmode.grayscale.images = 0.0
# c.colors.webpage.darkmode.policy.images = 'smart'
# c.colors.webpage.darkmode.policy.page = 'smart'
# c.colors.webpage.darkmode.threshold.background = 205
# c.colors.webpage.darkmode.threshold.text = 150
c.colors.webpage.preferred_color_scheme = 'dark'

# Completion
c.completion.cmd_history_max_items = 100
c.completion.delay = 0

# Default filesystem autocomplete suggestions for :open.
c.completion.favorite_paths = []

c.completion.height = '30%'
c.completion.min_chars = 1

c.completion.open_categories = [
    'searchengines',
    'quickmarks',
    'bookmarks',
    'history',
    'filesystem'
]

# Move on to the next part when there's only one possible completion left.
c.completion.quick = True

# Padding (in pixels) of the scrollbar handle in the completion window.
c.completion.scrollbar.padding = 0
c.completion.scrollbar.width = 6
c.completion.show = 'always'
c.completion.shrink = True

c.completion.timestamp_format = '%H:%M %d/%m/%Y'

# Execute the best-matching command on a partial match.
c.completion.use_best_match = True

c.completion.web_history.exclude = []
# Number of URLs to show in the web history. 0: no history / -1: unlimited
c.completion.web_history.max_items = -1

c.confirm_quit = ['never']

c.content.autoplay = True

c.content.blocking.enabled = True
c.content.blocking.hosts.block_subdomains = True
c.content.blocking.whitelist = []
c.content.headers.do_not_track = True

c.content.images = True

c.content.cookies.store = True
c.content.cookies.accept = "no-unknown-3rdparty"

# USER STYLE SHEETS
c.content.user_stylesheets = []

c.content.webgl = True
c.content.javascript.clipboard = "access-paste"

c.downloads.location.directory = "~/downloads/"
c.downloads.location.prompt = False
c.downloads.location.remember = True
c.downloads.location.suggestion = 'path'
# c.downloads.open_dispatcher = None
c.downloads.position = 'top'
c.downloads.remove_finished = 4000

c.editor.command = ['wezterm', '-e', 'nvim', '-c', 'normal {line}G{column0}l', '--', '{file}']
c.editor.encoding = 'utf-8'
c.editor.remove_file = True

# c.fileselect.folder.command = ['wezterm', '-e', 'ranger', '--choosedir={}']
# c.fileselect.handler = 'external'
# c.fileselect.multiple_files.command = ['wezterm', '-e', 'ranger', '--choosefiles={}']
# c.fileselect.single_file.command = ['wezterm', '-e', 'ranger', '--choosefile={}']

c.fonts.completion.category = 'bold default_size default_family'
c.fonts.completion.entry = 'default_size default_family'
c.fonts.contextmenu = 'default_size default_family'
c.fonts.debug_console = 'default_size default_family'
c.fonts.default_family = ['Cascadia Mono PL SemiLight']
c.fonts.default_size = '10pt'
c.fonts.hints = 'bold default_size default_family'
c.fonts.messages.error = 'bold default_size default_family'

# ############################### HINTS ############################# #
c.hints.auto_follow = 'unique-match'
c.hints.auto_follow_timeout = 0
c.hints.border = '1px solid #E1D2AB 0 0'
c.hints.chars = 'asdghklqwertyuiopzxcvbnmfj;'
# c.hints.dictionary = '/usr/share/dict/words'
# c.hints.hide_unmatched_rapid_hints = True
c.hints.leave_on_load = True
c.hints.min_chars = 1
c.hints.mode = 'letter'
c.hints.padding = {'top': 0, 'bottom': 0, 'left': 0, 'right': 0}
c.hints.radius = 0
c.hints.scatter = True
c.hints.uppercase = False
# c.hints.next_regexes = ['\\bnext\\b', '\\bmore\\b', '\\bnewer\\b', '\\b[>→≫]\\b', '\\b(>>|»)\\b', '\\bcontinue\\b']
# c.hints.prev_regexes = ['\\bprev(ious)?\\b', '\\bback\\b', '\\bolder\\b', '\\b[<←≪]\\b', '\\b(<<|«)\\b']
# c.hints.selectors = {'all': ['a', 'area', 'textarea', 'select', 'input:not([type="hidden"])', 'button', 'frame', 'iframe', 'img', 'link', 'summary', '[contenteditable]:not([contenteditable="false"])', '[onclick]', '[onmousedown]', '[role="link"]', '[role="option"]', '[role="button"]', '[role="tab"]', '[role="checkbox"]', '[role="menuitem"]', '[role="menuitemcheckbox"]', '[role="menuitemradio"]', '[ng-click]', '[ngClick]', '[data-ng-click]', '[x-ng-click]', '[tabindex]:not([tabindex="-1"])'], 'links': ['a[href]', 'area[href]', 'link[href]', '[role="link"][href]'], 'images': ['img'], 'media': ['audio', 'img', 'video'], 'url': ['[src]', '[href]'], 'inputs': ['input[type="text"]', 'input[type="date"]', 'input[type="datetime-local"]', 'input[type="email"]', 'input[type="month"]', 'input[type="number"]', 'input[type="password"]', 'input[type="search"]', 'input[type="tel"]', 'input[type="time"]', 'input[type="url"]', 'input[type="week"]', 'input:not([type])', '[contenteditable]:not([contenteditable="false"])', 'textarea']}


c.input.forward_unbound_keys = 'auto'
c.input.insert_mode.auto_enter = True
c.input.insert_mode.auto_leave = True
c.input.insert_mode.auto_load = False
c.input.insert_mode.leave_on_load = True
c.input.partial_timeout = 0
c.input.mouse.rocker_gestures = True

# Mode to change to when focusing on a tab/URL changes.
# Type: String
# Valid values:
# - normal
# - insert
# - passthrough
# c.input.mode_override = None

c.input.mouse.back_forward_buttons = True

c.keyhint.blacklist = []
c.keyhint.delay = 0
c.keyhint.radius = 0

c.new_instance_open_target = 'tab'
c.new_instance_open_target_window = 'last-focused'
c.prompt.filebrowser = True
c.prompt.radius = 0

# Additional arguments to pass to Qt, without leading `--`. With
c.qt.args = []

c.qt.chromium.process_model = "process-per-site"

c.session.lazy_restore = True


# Additional environment variables to set.
# c.qt.environ = {}

# - always: Always show the scrollbar.
# - never: Never show the scrollbar.
# - when-searching: Show the scrollbar when searching for text in the webpage. With the QtWebKit backend, this is equal to `never`.
# - overlay: Show an overlay scrollbar. On macOS, this is unavailable and equal to `when-searching`; with the QtWebKit backend, this is equal to `never`. Enabling/disabling overlay scrollbars requires a restart.
c.scrolling.bar = 'never'
# c.scrolling.smooth = False

# c.search.ignore_case = 'smart'
# c.search.incremental = True
# c.search.wrap = True

# Padding (in pixels) for the statusbar.
c.statusbar.padding = {'top': 1, 'bottom': 1, 'left': 0, 'right': 0}
c.statusbar.position = 'bottom'
c.statusbar.show = 'always'
# - url: Current page URL.
# - scroll: Percentage of the current page position like `10%`.
# - scroll_raw: Raw percentage of the current page position like `10`.
# - history: Display an arrow when possible to go back/forward in history.
# - tabs: Current active tab, e.g. `2`.
# - keypress: Display pressed keys when composing a vi command.
# - progress: Progress bar for the current page loading.
# - text:foo: Display the static text after the colon, `foo` in the example.
c.statusbar.widgets = ['keypress', 'url', 'scroll_raw', 'progress']

c.tabs.background = True
# c.tabs.favicons.scale = 1.0
# - always: Always show favicons.
# - never: Always hide favicons.
# - pinned: Show favicons only on pinned tabs.
c.tabs.favicons.show = 'pinned'
# c.tabs.focus_stack_size = 10
# c.tabs.indicator.padding = {'top': 2, 'bottom': 2, 'left': 0, 'right': 4}
c.tabs.indicator.width = 1
c.tabs.last_close = 'default-page'
c.tabs.mousewheel_switching = False
# c.tabs.padding = {'top': 0, 'bottom': 0, 'left': 5, 'right': 5}
# c.tabs.pinned.frozen = True
# c.tabs.pinned.shrink = True
c.tabs.position = 'top'
# - prev: Select the tab which came before the closed one (left in horizontal, above in vertical).
# - next: Select the tab which came after the closed one (right in horizontal, below in vertical).
# - last-used: Select the previously selected tab.
c.tabs.select_on_remove = 'prev'
# - always: Always show the tab bar.
# - never: Always hide the tab bar.
# - multiple: Hide the tab bar if only one tab is open.
# - switching: Show the tab bar when switching tabs.
# c.tabs.show = 'always'
c.tabs.tabs_are_windows = False
# c.tabs.title.alignment = 'left'
c.tabs.title.format = '{audio}{current_title}'
c.tabs.title.format_pinned = ''
c.tabs.tooltips = False
c.tabs.wrap = True

c.window.hide_decoration = True
c.window.title_format = '{current_title}{title_sep}qutebrowser'

c.window.transparent = True

# Default zoom level.
# c.zoom.default = '100%'
# c.zoom.levels = ['25%', '33%', '50%', '67%', '75%', '90%', '100%', '110%', '125%', '150%', '175%', '200%', '250%', '300%', '400%', '500%']
# c.zoom.mouse_divider = 512
# c.zoom.text_only = False

c.bindings.default = {}
c.bindings.key_mappings = {
    # '<Ctrl-[>': '<Escape>',
    # '<Ctrl-6>': '<Ctrl-^>',
    # '<Ctrl-M>': '<Return>',
    # '<Ctrl-J>': '<Return>',
    # '<Ctrl-I>': '<Tab>',
    # '<Shift-Return>': '<Return>',
    '<Enter>': '<Return>',
    '<Shift-Enter>': '<Shift-Return>',
    '<Ctrl-Enter>': '<Ctrl-Return>',
}

class Head:
    prefix = ""

    def key(self, key, func):
        config.bind("|" + self.prefix + key, func)

def head_create(page_name):
    p = Head()
    p.prefix = page_name.lower()[0]
    fake = "_" + page_name
    config.bind(";" + p.prefix, fake)
    c.aliases[fake] = "fake-key --global |" + p.prefix;
    return p

h_page = head_create("Page")
h_page.key('u', 'navigate up -t')
h_page.key('s', 'view-source')
h_page.key('d', 'devtools')
h_page.key('f', 'devtools-focus')
h_page.key('h', 'devtools left')
h_page.key('j', 'devtools bottom')
h_page.key('k', 'devtools top')
h_page.key('l', 'devtools right')
h_page.key('w', 'devtools window')

h_tab = head_create("Tab")
h_tab.key('c', 'tab-clone')
h_tab.key('g', 'tab-give')
h_tab.key('o', 'tab-only')
h_tab.key('C', 'tab-close -o')
h_tab.key('w', 'set tabs.tabs_are_windows true')
h_tab.key('W', 'set tabs.tabs_are_windows false')
h_tab.key('R', 'set input.mouse.rocker_gestures true')
h_tab.key('r', 'set input.mouse.rocker_gestures false')

h_mark = head_create("Mark")
h_mark.key('q', 'cmd-set-text -s :quickmark-load')
h_mark.key('Q', 'cmd-set-text -s :quickmark-load -t')
h_mark.key('w', 'cmd-set-text -s :quickmark-load -w')
h_mark.key('h', 'history')
h_mark.key('a', 'bookmark-add')
h_mark.key('l', 'bookmark-list')
h_mark.key('L', 'bookmark-list --jump')
h_mark.key('b', 'cmd-set-text -s :bookmark-load')
h_mark.key('B', 'cmd-set-text -s :bookmark-load -t')
h_mark.key('W', 'cmd-set-text -s :bookmark-load -w')

h_download = head_create("Download")
h_download.key('d', 'download')
h_download.key('c', 'download-cancel')
h_download.key('C', 'download-clear')

h_hint = head_create("Hint")
h_hint.key('i', 'hint images')
h_hint.key('I', 'hint images tab')
h_hint.key('l', 'hint links fill :open {hint-url}')
h_hint.key('L', 'hint links fill :open -t -r {hint-url}')
h_hint.key('r', 'hint --rapid links tab-bg')
h_hint.key('R', 'hint --rapid links window')
h_hint.key('a', 'hint all tab-fg')
h_hint.key('A', 'hint all tab-bg')
h_hint.key('w', 'hint all window')
h_hint.key('d', 'hint links download')
h_hint.key('D', 'hint images download')
h_hint.key('h', 'hint all hover')
h_hint.key('t', 'hint inputs')
h_hint.key('T', 'hint inputs --first')
h_hint.key('y', 'hint links yank')
h_hint.key('Y', 'hint links yank-primary')

h_conf = head_create("Config")
h_conf.key('c', 'config-cycle -p -t -u {url} content.cookies.accept all no-3rdparty never ;; reload')
h_conf.key('C', 'config-cycle -p -t -u *://{url:host}/* content.cookies.accept all no-3rdparty never ;; reload')
h_conf.key('i', 'config-cycle -p -t -u {url} content.images ;; reload')
h_conf.key('I', 'config-cycle -p -t -u *://{url:host}/* content.images ;; reload')
h_conf.key('p', 'config-cycle -p -t -u {url} content.plugins ;; reload')
h_conf.key('P', 'config-cycle -p -t -u *://{url:host}/* content.plugins ;; reload')
h_conf.key('j', 'config-cycle -p -t -u {url} content.javascript.enabled ;; reload')
h_conf.key('J', 'config-cycle -p -t -u *://{url:host}/* content.javascript.enabled ;; reload')
h_conf.key('r', 'config-source')

h_yank = head_create("Yank")
h_yank.key('l', 'yank url')

h_view = head_create("View")
h_view.key('m', 'spawn --detach mpv --force-window {url}')
h_view.key('h', 'hint links spawn --detach mpv --force-window {hint-url}')

config.bind('<Ctrl-Shift-M>', 'spawn --detach mpv --force-window {url}')
config.bind('<Ctrl-M>', 'hint links spawn --detach mpv --force-window {hint-url}')

config.bind(';Q', 'quit')
config.bind(';q', 'quit --save')
config.bind(';w', 'save')

# Bindings for normal mode
config.bind("`", 'mode-enter jump_mark')
config.bind('m', 'mode-enter set_mark')
config.bind('~', 'cmd-set-text -s :quickmark-load -t')
config.bind('M', 'quickmark-save')

config.bind('<Ctrl-V>', 'mode-enter passthrough')
config.bind('V', 'mode-enter caret ;; selection-toggle --line')
config.bind('i', 'mode-enter insert')
config.bind('v', 'mode-enter caret')

config.bind('+', 'zoom-in')
config.bind('-', 'zoom-out')
config.bind('=', 'zoom')

config.bind('.', 'cmd-repeat-last')
config.bind('/', 'cmd-set-text /')
config.bind(':', 'cmd-set-text :')
config.bind('?', 'cmd-set-text ?')
config.bind('@', 'macro-run')
config.bind('s', 'hint')
config.bind('S', 'hint all tab')
config.bind('<Ctrl-Shift-S>', 'hint all tab-bg')
config.bind('H', 'back')
config.bind('L', 'forward')
config.bind('n', 'search-next')
config.bind('N', 'search-prev')
config.bind('o', 'cmd-set-text -s :open')
config.bind('O', 'cmd-set-text -s :open -t')
config.bind('<Ctrl-Shift-O>', 'cmd-set-text -s :open -w')
config.bind('R', 'reload -f')
config.bind('P', 'open -t -- {primary}')
config.bind('p', 'open -t -- {clipboard}')

config.bind('<Ctrl-l>', 'cmd-set-text :open {url:pretty}')
config.bind('<Ctrl-1>', 'tab-focus 1')
config.bind('<Ctrl-2>', 'tab-focus 2')
config.bind('<Ctrl-3>', 'tab-focus 3')
config.bind('<Ctrl-4>', 'tab-focus 4')
config.bind('<Ctrl-5>', 'tab-focus 5')
config.bind('<Ctrl-6>', 'tab-focus 6')
config.bind('<Ctrl-7>', 'tab-focus 7')
config.bind('<Ctrl-8>', 'tab-focus 8')
config.bind('<Ctrl-9>', 'tab-focus -1')
config.bind('<Alt-m>', 'tab-mute')
# config.bind('<Ctrl-A>', 'navigate increment')
# config.bind('<Ctrl-Alt-p>', 'print')
# config.bind('<Ctrl-B>', 'scroll-page 0 -1')
# config.bind('<Ctrl-D>', 'scroll-page 0 0.5')
config.bind('<Ctrl-F5>', 'reload -f')
config.bind('<Escape>', 'clear-keychain ;; search ;; fullscreen --leave')
config.bind('<F11>', 'fullscreen')
config.bind('<F5>', 'reload')
config.bind('<Return>', 'selection-follow')
config.bind('<back>', 'back')
config.bind('<forward>', 'forward')
# config.bind('<Ctrl-F>', 'scroll-page 0 1')
config.bind('<Ctrl-N>', 'open -w')
config.bind('<Ctrl-Shift-N>', 'open -p')

config.bind('<Alt-,>', 'tab-prev')
config.bind('<Alt-.>', 'tab-next')
config.bind('<Ctrl-W>', 'tab-close')

# LINK: https://github.com/qutebrowser/qutebrowser/issues/3736
config.bind('<', 'tab-move -')
config.bind('>', 'tab-move +')
config.bind('<Alt-Shift-,>', 'tab-move -')
config.bind('<Alt-Shift-.>', 'tab-move +')

config.bind('<Ctrl-Q>', 'quit')
config.bind('<Ctrl-Return>', 'selection-follow -t')
config.bind('<Ctrl-Shift-T>', 'undo')
config.bind('<Ctrl-Shift-W>', 'close')
config.bind('<Ctrl-T>', 'open -t')
config.bind('<Shift-Space>', 'scroll-page 0 -0.5')
config.bind('<Ctrl-Space>', 'scroll-page 0 -0.5')
config.bind('<Space>', 'scroll-page 0 0.5')
config.bind('<PgUp>', 'scroll-page 0 -1')
config.bind('<PgDown>', 'scroll-page 0 1')
config.bind('<Ctrl-u>', 'scroll-page 0 -1')
config.bind('<Ctrl-d>', 'scroll-page 0 1')
config.bind('<Ctrl-h>', 'home')
config.bind('<Ctrl-p>', 'tab-pin')
config.bind('<Ctrl-s>', 'stop')


config.bind('gg', 'scroll-to-perc 0')
config.bind('G', 'scroll-to-perc')
config.bind('gt', 'cmd-set-text -s :tab-select')
config.bind('gd', 'navigate next')
config.bind('gu', 'navigate prev')
config.bind('gU', 'navigate up')
config.bind('gi', 'hint inputs')
config.bind('gl', 'hint links')

config.bind('h', 'scroll left')
config.bind('j', 'scroll down')
config.bind('k', 'scroll up')
config.bind('l', 'scroll right')

config.bind('q', 'macro-record')
config.bind('r', 'reload')

config.bind('t', 'cmd-set-text -sr :tab-focus')
config.bind('u', 'back --quiet')
config.bind('U', 'undo -w')
config.bind('<Ctrl-R>', 'forward --quiet')
config.bind('<Ctrl-Shift-R>', 'forward -t --quiet')
config.bind('YD', 'yank domain -s')
config.bind('YM', 'yank inline [{title}]({url}) -s')
config.bind('YP', 'yank pretty-url -s')
config.bind('YT', 'yank title -s')
config.bind('Yy', 'yank')
config.bind('YY', 'yank -s')
config.bind('Yd', 'yank domain')
config.bind('Ym', 'yank inline [{title}]({url})')
config.bind('Yp', 'yank pretty-url')
config.bind('Yt', 'yank title')
config.bind('y', 'yank selection')
# config.bind('<Ctrl+Shift+C>', 'yank selection')

# Bindings for caret mode
config.bind('$', 'move-to-end-of-line', mode='caret')
config.bind('0', 'move-to-start-of-line', mode='caret')
config.bind('<Ctrl-Space>', 'selection-drop', mode='caret')
config.bind('<Escape>', 'mode-leave', mode='caret')
config.bind('<Return>', 'yank selection', mode='caret')
config.bind('<Space>', 'selection-toggle', mode='caret')
config.bind('G', 'move-to-end-of-document', mode='caret')
config.bind('H', 'scroll left', mode='caret')
config.bind('J', 'scroll down', mode='caret')
config.bind('K', 'scroll up', mode='caret')
config.bind('L', 'scroll right', mode='caret')
config.bind('V', 'selection-toggle --line', mode='caret')
config.bind('Y', 'yank selection -s', mode='caret')
config.bind('[', 'move-to-start-of-prev-block', mode='caret')
config.bind(']', 'move-to-start-of-next-block', mode='caret')
config.bind('b', 'move-to-prev-word', mode='caret')
config.bind('c', 'mode-enter normal', mode='caret')
config.bind('e', 'move-to-end-of-word', mode='caret')
config.bind('gg', 'move-to-start-of-document', mode='caret')
config.bind('h', 'move-to-prev-char', mode='caret')
config.bind('j', 'move-to-next-line', mode='caret')
config.bind('k', 'move-to-prev-line', mode='caret')
config.bind('l', 'move-to-next-char', mode='caret')
config.bind('o', 'selection-reverse', mode='caret')
config.bind('v', 'selection-toggle', mode='caret')
config.bind('w', 'move-to-next-word', mode='caret')
config.bind('y', 'yank selection', mode='caret')
config.bind('{', 'move-to-end-of-prev-block', mode='caret')
config.bind('}', 'move-to-end-of-next-block', mode='caret')

# Bindings for command mode
config.bind('<Alt-B>', 'rl-backward-word', mode='command')
config.bind('<Alt-Backspace>', 'rl-backward-kill-word', mode='command')
config.bind('<Alt-D>', 'rl-kill-word', mode='command')
config.bind('<Alt-F>', 'rl-forward-word', mode='command')
config.bind('<Ctrl-?>', 'rl-delete-char', mode='command')
config.bind('<Ctrl-A>', 'rl-beginning-of-line', mode='command')
config.bind('<Ctrl-B>', 'rl-backward-char', mode='command')
config.bind('<Ctrl-C>', 'completion-item-yank', mode='command')
config.bind('<Ctrl-D>', 'completion-item-del', mode='command')
config.bind('<Ctrl-E>', 'rl-end-of-line', mode='command')
config.bind('<Ctrl-F>', 'rl-forward-char', mode='command')
config.bind('<Ctrl-H>', 'rl-backward-delete-char', mode='command')
config.bind('<Ctrl-K>', 'rl-kill-line', mode='command')
config.bind('<Ctrl-N>', 'command-history-next', mode='command')
config.bind('<Ctrl-P>', 'command-history-prev', mode='command')
config.bind('<Ctrl-Return>', 'command-accept --rapid', mode='command')
config.bind('<Ctrl-Shift-C>', 'completion-item-yank --sel', mode='command')
config.bind('<Ctrl-Shift-Tab>', 'completion-item-focus prev-category', mode='command')
config.bind('<Ctrl-Shift-W>', 'rl-filename-rubout', mode='command')
config.bind('<Ctrl-Tab>', 'completion-item-focus next-category', mode='command')
config.bind('<Ctrl-U>', 'rl-unix-line-discard', mode='command')
config.bind('<Ctrl-W>', 'rl-rubout " "', mode='command')
config.bind('<Ctrl-Y>', 'rl-yank', mode='command')
config.bind('<Down>', 'completion-item-focus --history next', mode='command')
config.bind('<Escape>', 'mode-leave', mode='command')
config.bind('<PgDown>', 'completion-item-focus next-page', mode='command')
config.bind('<PgUp>', 'completion-item-focus prev-page', mode='command')
config.bind('<Return>', 'command-accept', mode='command')
config.bind('<Shift-Delete>', 'completion-item-del', mode='command')
config.bind('<Shift-Tab>', 'completion-item-focus prev', mode='command')
config.bind('<Tab>', 'completion-item-focus next', mode='command')
config.bind('<Up>', 'completion-item-focus --history prev', mode='command')

# Bindings for hint mode
config.bind('<Ctrl-B>', 'hint all tab-bg', mode='hint')
config.bind('<Ctrl-F>', 'hint links', mode='hint')
config.bind('<Ctrl-R>', 'hint --rapid links tab-bg', mode='hint')
config.bind('<Escape>', 'mode-leave', mode='hint')
config.bind('<Return>', 'hint-follow', mode='hint')

# Bindings for insert mode
config.bind('<Ctrl-E>', 'edit-text', mode='insert')
config.bind('<Escape>', 'mode-leave', mode='insert')
config.bind('<Shift-Escape>', 'fake-key <Escape>', mode='insert')
config.bind('<Shift-Ins>', 'insert-text -- {primary}', mode='insert')

# Bindings for passthrough mode
config.bind('<Shift-Escape>', 'mode-leave', mode='passthrough')

# Bindings for prompt mode
config.bind('<Alt-B>', 'rl-backward-word', mode='prompt')
config.bind('<Alt-Backspace>', 'rl-backward-kill-word', mode='prompt')
config.bind('<Alt-D>', 'rl-kill-word', mode='prompt')
config.bind('<Alt-F>', 'rl-forward-word', mode='prompt')
config.bind('<Alt-Shift-Y>', 'prompt-yank --sel', mode='prompt')
config.bind('<Alt-Y>', 'prompt-yank', mode='prompt')
config.bind('<Ctrl-?>', 'rl-delete-char', mode='prompt')
config.bind('<Ctrl-A>', 'rl-beginning-of-line', mode='prompt')
config.bind('<Ctrl-B>', 'rl-backward-char', mode='prompt')
config.bind('<Ctrl-E>', 'rl-end-of-line', mode='prompt')
config.bind('<Ctrl-F>', 'rl-forward-char', mode='prompt')
config.bind('<Ctrl-H>', 'rl-backward-delete-char', mode='prompt')
config.bind('<Ctrl-K>', 'rl-kill-line', mode='prompt')
config.bind('<Ctrl-P>', 'prompt-open-download --pdfjs', mode='prompt')
config.bind('<Ctrl-Shift-W>', 'rl-filename-rubout', mode='prompt')
config.bind('<Ctrl-U>', 'rl-unix-line-discard', mode='prompt')
config.bind('<Ctrl-W>', 'rl-rubout " "', mode='prompt')
config.bind('<Ctrl-X>', 'prompt-open-download', mode='prompt')
config.bind('<Ctrl-Y>', 'rl-yank', mode='prompt')
config.bind('<Down>', 'prompt-item-focus next', mode='prompt')
config.bind('<Escape>', 'mode-leave', mode='prompt')
config.bind('<Return>', 'prompt-accept', mode='prompt')
config.bind('<Shift-Tab>', 'prompt-item-focus prev', mode='prompt')
config.bind('<Tab>', 'prompt-item-focus next', mode='prompt')
config.bind('<Up>', 'prompt-item-focus prev', mode='prompt')

# Bindings for register mode
config.bind('<Escape>', 'mode-leave', mode='register')

# Bindings for yesno mode
config.bind('<Alt-Shift-Y>', 'prompt-yank --sel', mode='yesno')
config.bind('<Alt-Y>', 'prompt-yank', mode='yesno')
config.bind('<Escape>', 'mode-leave', mode='yesno')
config.bind('<Return>', 'prompt-accept', mode='yesno')
config.bind('N', 'prompt-accept --save no', mode='yesno')
config.bind('Y', 'prompt-accept --save yes', mode='yesno')
config.bind('n', 'prompt-accept no', mode='yesno')
config.bind('y', 'prompt-accept yes', mode='yesno')

# ######################## THEMES ######################## #

allowed_themes = [ "gruvbox", "despair" ]

selected_theme = "gruvbox"

if os.path.exists(config_home + "/env_theme_name"):
    f = open(config_home + "/env_theme_name")
    theme_conf = f.readlines()[0][:-1]
    if theme_conf in allowed_themes:
        selected_theme = theme_conf
    f.close()

BG        = "#282828"
GRAY      = "#928374"
FG        = "#ebdbb2"
RED       = "#cc231d"
GREEN     = "#98971a"
YELLOW    = "#d79921"
BLUE      = "#458588"
PURPLE    = "#b16286"
AQUA      = "#689d6a"
ORANGE    = "#d65d0e"
LT_GRAY   = "#a89984"
LT_RED    = "#fb4934"
LT_GREEN  = "#b8bb26"
LT_YELLOW = "#fabd2f"
LT_BLUE   = "#83a598"
LT_PURPLE = "#d3869b"
LT_AQUA   = "#8ec07c"
LT_ORANGE = "#fe8019"
BG0_H     = "#1d2021"
BG0       = "#282828"
BG0_S     = "#32302f"
BG1       = "#3c3836"
BG2       = "#504945"
BG3       = "#665c54"
BG4       = "#7c6f64"
BG5       = "#928374"
FG4       = "#a89984"
FG3       = "#bdae93"
FG2       = "#d5c4a1"
FG1       = "#ebdbb2"
FG0       = "#fbf1c7"

if selected_theme == "despair":
    BG        = "#101010"
    GRAY      = "#7c7c7c"
    FG        = "#8e8e8e"
    RED       = "#b9b9b9"
    GREEN     = "#903a3a"
    YELLOW    = "#ce5252"
    BLUE      = "#6d7144"
    PURPLE    = "#9ca54e"
    AQUA      = "#af8431"
    ORANGE    = "#f0c674"
    LT_GRAY   = "#61837e"
    LT_RED    = "#5f819d"
    LT_GREEN  = "#92729f"
    LT_YELLOW = "#b48ac4"
    LT_BLUE   = "#61837e"
    LT_PURPLE = "#73b8af"
    LT_AQUA   = "#50616f"
    LT_ORANGE = "#5f819d"
    BG0_H     = "#101010"
    BG0       = "#101010"
    BG0_S     = "#252525"
    BG1       = "#252525"
    BG2       = "#252525"
    BG3       = "#252525"
    BG4       = "#8e8e8e"
    BG5       = "#8e8e8e"
    FG4       = "#8e8e8e"
    FG3       = "#8e8e8e"
    FG2       = "#b9b9b9"
    FG1       = "#e3e3e3"
    FG0       = "#f7f7f7"

# color of the completion widget category headers.
c.colors.completion.category.bg = FG4
c.colors.completion.category.border.bottom = FG4
c.colors.completion.category.border.top = FG4
c.colors.completion.category.fg = BG

# color of the completion widget.
c.colors.completion.even.bg = BG2
c.colors.completion.odd.bg = BG2
c.colors.completion.fg = FG
c.colors.completion.item.selected.bg = LT_BLUE
c.colors.completion.item.selected.border.bottom = LT_BLUE
c.colors.completion.item.selected.border.top = LT_BLUE
c.colors.completion.item.selected.fg = BG
c.colors.completion.item.selected.match.fg = BG0_S
c.colors.completion.match.fg = LT_BLUE

# color of completion scrollbar
c.colors.completion.scrollbar.bg = BG2
c.colors.completion.scrollbar.fg = FG4

# color of items in the context menu
c.colors.contextmenu.disabled.bg = BG
c.colors.contextmenu.disabled.fg = FG4
c.colors.contextmenu.menu.bg = BG
c.colors.contextmenu.menu.fg = FG
c.colors.contextmenu.selected.bg = BG2
c.colors.contextmenu.selected.fg = FG

# color for the download bar.
c.colors.downloads.bar.bg = BG
c.colors.downloads.error.bg = BG
c.colors.downloads.error.fg = RED
c.colors.downloads.start.bg = BG
c.colors.downloads.start.fg = AQUA
c.colors.downloads.stop.bg = BG
c.colors.downloads.stop.fg = AQUA
c.colors.downloads.system.bg = 'none'
c.colors.downloads.system.fg = 'none'

# color for hints
c.colors.hints.bg = FG
c.colors.hints.fg = BG
c.colors.hints.match.fg = ORANGE

# color of the keyhint widget.
c.colors.keyhint.bg = BG
c.colors.keyhint.fg = FG
c.colors.keyhint.suffix.fg = LT_BLUE

# Background color of an error message.
c.colors.messages.error.bg = BG
c.colors.messages.error.border = BG
c.colors.messages.error.fg = LT_RED

# Background color of an info message.
c.colors.messages.info.bg = BG
c.colors.messages.info.border = BG
c.colors.messages.info.fg = LT_BLUE

# Background color of a warning message.
c.colors.messages.warning.bg = BG
c.colors.messages.warning.border = BG
c.colors.messages.warning.fg = LT_ORANGE

# Background color for prompts.
# Type: QssColor
c.colors.prompts.bg = BG
c.colors.prompts.border = '1px solid ' + BG + ' 0 0 0'
c.colors.prompts.fg = FG
c.colors.prompts.selected.bg = BG2
c.colors.prompts.selected.fg = FG

# Background color of the statusbar in caret mode.
c.colors.statusbar.caret.bg = LT_ORANGE
c.colors.statusbar.caret.fg = BG
# line selection
c.colors.statusbar.caret.selection.bg = LT_ORANGE
c.colors.statusbar.caret.selection.fg = BG

# Background color of the statusbar in command mode.
c.colors.statusbar.command.bg = BG
c.colors.statusbar.command.fg = FG

# Background color of the statusbar in private browsing + command mode.
c.colors.statusbar.command.private.bg = BG
c.colors.statusbar.command.private.fg = FG

# Background color of the statusbar in insert mode.
c.colors.statusbar.insert.bg = LT_BLUE
c.colors.statusbar.insert.fg = BG

# Background color of the statusbar.
c.colors.statusbar.normal.bg = BG
c.colors.statusbar.normal.fg = FG

# Background color of the statusbar in passthrough mode.
c.colors.statusbar.passthrough.bg = LT_BLUE
c.colors.statusbar.passthrough.fg = BG

# Background color of the statusbar in private browsing mode.
c.colors.statusbar.private.bg = BG
c.colors.statusbar.private.fg = LT_BLUE

# Background color of the progress bar.
c.colors.statusbar.progress.bg = BG2

# Foreground color of the URL in the statusbar on error.
c.colors.statusbar.url.error.fg = LT_RED
c.colors.statusbar.url.fg = FG
c.colors.statusbar.url.hover.fg = FG
c.colors.statusbar.url.success.http.fg = FG
c.colors.statusbar.url.success.https.fg = FG
c.colors.statusbar.url.warn.fg = LT_ORANGE

# Background color of the tab bar.
c.colors.tabs.bar.bg = BG

# Background color of unselected even tabs.
c.colors.tabs.even.bg = BG
c.colors.tabs.even.fg = BG4
c.colors.tabs.odd.bg = BG
c.colors.tabs.odd.fg = BG4

# Color for the tab indicator on errors.
c.colors.tabs.indicator.error = LT_RED
c.colors.tabs.indicator.start = LT_AQUA
c.colors.tabs.indicator.stop = LT_AQUA
c.colors.tabs.indicator.system = 'none'


# Background color of pinned unselected even tabs.
c.colors.tabs.pinned.even.bg = BG
c.colors.tabs.pinned.even.fg = BG4
c.colors.tabs.pinned.odd.bg = BG
c.colors.tabs.pinned.odd.fg = BG4

# Background color of pinned selected even tabs.
c.colors.tabs.pinned.selected.even.bg = BG1
c.colors.tabs.pinned.selected.even.fg = FG
c.colors.tabs.pinned.selected.odd.bg = BG1
c.colors.tabs.pinned.selected.odd.fg = FG

# Background color of selected even tabs.
c.colors.tabs.selected.even.bg = BG1
c.colors.tabs.selected.even.fg = FG
c.colors.tabs.selected.odd.bg = BG1
c.colors.tabs.selected.odd.fg = FG

