#!/usr/bin/env bash
# Usage:
#     prog_name                    - Show docset picker and show docs for selected docset
#     prog_name <docset>           - Show docs for <docset>
#     prog_name <command>          - Show docset picker and execute <command>
#     prog_name <command> <docset> - Execute <command> for <docset>
#
# Notes:
#     <command> - must be a full command name
#     <docset>  - can be a partial name and will be fuzzy matched
#
# Options:
#     -h, --help  - This help information
#     -c, --check - Check if script can be succesfully ran
#
# Commands:
#     get         - Download new docset
#     regen       - Regenerate pages for docset
#     purge       - Delete docset
#     check       - Same as --check flag
#     help        - Same as --help flag
#

# Select docs from devdocs.io using a fuzzy-finder for display at the CLI
# Deps: tidy, xmlstarlet, jq, lynx, fzy, curl, POSIX, lr (leahneukirchen)
# (This uses a few shell scripts from $HOME/bin. Look there for reference.)

NAME=$(basename "$0")
TEMP="${TMPDIR-/tmp}/${NAME}.${$}.$(awk \
    'BEGIN {srand(); printf "%d\n", rand() * 10^10}')"

__has() {
    command -v $@ 2>&1 >/dev/null && return 0 || return 1
}

browser=lynx
__has w3m && browser=w3m
__has elinks && browser=elinks

init_cache_dir() {
    mkdir -p "$DEVDOCS_DIR"
    node_idx="$DEVDOCS_DIR/index.js"
    node_pkg="$DEVDOCS_DIR/package.json"

    idx_js='const express = require("express");
const path = require("path");
const fs = require("fs");

const app = express();

app.use(express.json());
app.use(express.static(path.join(__dirname, "."), { extensions: ["html", "htm", "xhtml"] }));

app.all("*", (req, res) => {
    const nurl = req.url.replace(/\/$/, "") + ".html"
    const fname = path.join(__dirname, nurl);
    if (fs.existsSync(fname)) {
        res.redirect(nurl);
    } else {
        res.writeHead(200, { "Content-Type": "text/html" });
        res.status(404).end(`<h1>404 Specified page not found</h1><h2>Your current url is "${req.url}".</h2>`);
    }
});

const port = process.env.PORT || 2517;

app.listen(port, (err, res) => {
    if (err) {
        console.log(err);
        return res.status(500).send(err.message);
    } else {
        console.log("[INFO] Server Running on port:", port);
    }
});

module.exports = app; '

    package_json='{
  "name": "devdocs-local",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "serve": "node index.js"
  },
  "author": "",
  "license": "ISC",
  "description": "",
  "dependencies": {
    "express": "^4.21.1"
  }
} '

    echo "$idx_js" > "$node_idx"
    echo "$package_json" > "$node_pkg"

    npm install --prefix "$DEVDOCS_DIR"
}

[ ! -n "$DEVDOCS_DIR" ] && DEVDOCS_DIR="$XDG_DATA_HOME/devdocs"
[ "$DEVDOCS_DIR" = "/devdocs" ] && DEVDOCS_DIR="$HOME/.local/share/devdocs"
[ ! -d "$DEVDOCS_DIR" ] && init_cache_dir

list() {
    # Find the docs JavaScript and try to extract the slug and mtime values.

    curl -sSL https://devdocs.io/docs.json | jq -r '.[] | [.slug, .mtime] | @tsv'
}

gen_pages() {
    [ ! -n "$@" ] && exit 1
    slug="$@"
    lang_dir="${DEVDOCS_DIR}/${slug}"

    did_index=0

    [ -d "${lang_dir}/pages" ] && rm -rf "${lang_dir}/pages"
    mkdir -p "${lang_dir}/pages"

    page_list="$(jq -r '.entries[] | "\(.path)"' "${lang_dir}/index.json")"
    page_count=$(echo "$page_list" | wc -l)
    current_page=1

    echo "$page_list" | while read line; do
        page="$(echo -e "$line" | cut -d "#" -f 1)"
        if [[ "$line" == *"#"* ]]; then
            if ! ( [[ "$(basename "$page")" == "index" ]] && [[ $did_index -eq 0 ]] ); then
                continue
            else
                did_index=1
            fi
        fi

        dir_name="$(dirname "${lang_dir}/pages/${page}.html")"
        [ ! -d "$dir_name" ] && mkdir -p "$dir_name"

        idx="$page"
        if ! [[ "$page" == *".html" || "$page" == *".xhtml" ]]; then
            page="$page.html"
        fi
        echo "[$current_page/$page_count] Writing ${page}"
        jq -r ".\"${idx}\"" \
            <"${lang_dir}/db.json" \
            >"${lang_dir}/pages/${page}"

        printf "\033[1A\033[K"
        ((++current_page))
    done
    echo "Finished generating pages for ${slug}"
}

regen() {
    lr "$DEVDOCS_DIR" -1 -s -t 'type == d' -t '!type == d || depth > 0' |
        gen_pages "$(fzf --layout="reverse" --height=35% --prompt="Choose docs > " -0 -q "$@")"
        # gen_pages "$(fzy -p 'Choose docs > ')"

}

download() {
    # Download the docsets to a deterministic location.

    while read -r slug mtime; do
        test -n "$slug" || return

        ddir="${DEVDOCS_DIR}/${slug}"

        mkdir -p "$ddir"
        cd "$ddir"

        if [ -r "${ddir}/mtime" ]; then
            $(ls "${ddir}/mtime" 1>&2)
            old_mtime=$(cat "${ddir}/mtime")

            if [ "$old_mtime" -ge "$mtime" ]; then
                printf 'Up-to-date %s\n' "$slug" 1>&2
                continue
            else
                printf 'Updating %s\n' "$slug" 1>&2
            fi
        else
            printf 'Installing %s\n' "$slug" 1>&2
        fi

        printf '%s\n' "$mtime" >mtime
        curl -C - -sS -o index.json "https://devdocs.io/docs/${slug}/index.json?${mtime}"
        curl -C - -sS -o db.json "https://documents.devdocs.io/${slug}/db.json?${mtime}"

        gen_pages "${slug}"

        echo "Finished downloading docs for ${slug}"
    done
}

get() {
    list | fzf --layout="reverse" --height=35% --prompt="Choose a docset > " -0 -q "$@" | download
    # if [ $# -eq 0 ]; then
    #     # list | fzf --layout="reverse" --height=35% --prompt="Choose a docset > " -0 -q "$@" | download
    #     # list | fzy -p 'Choose a docset > ' | download
    # else
    #     list | awk '
    #         BEGIN {
    #             for (i = 1; i < length(ARGV); i += 1) {
    #                 docs[ARGV[i]] = 1; ARGV[i] = ""
    #             }
    #         }

    #         docs[$1] { print $0 }
    #     ' "$@" | download
    # fi
}

# get_from() {
#     jq -r '.docs | split("/")[]' "${1:?Missing Devdocs Prefs export JSON}" |
#         xe -N0 "$0" choose
# }

doc_for() {
    echo "$@" | {
        read -r slug
        test -n "$slug" || return

        if [ ! -d "$DEVDOCS_DIR/$slug" ]; then
            dirs="$(lr "$DEVDOCS_DIR" -1 -s -t 'type == d' -t '!type == d || depth > 0' -t 'name != "node_modules"')"
            lang="$(echo "$dirs" | fzf --layout="reverse" --height=35% --prompt="Choose docs > " -1 -0 -q "$slug")"
            [ ! -n "$lang" ] && exit 1
            slug="$lang"
        fi

        jq -r '.entries[] | "\(.name) --- \(.path) --- (\(.type))"' \
            "${DEVDOCS_DIR}/${slug}/index.json" |
            fzf --layout="reverse" --height=35% --prompt="Chose a topic > " |
            # fzy -p 'Choose a topic > ' |
            awk -F " --- " '{
                h = index($2, "#")
                if (h == 0) {
                    print $2
                } else {
                    print substr($2, 1, h - 1), substr($2, h)
                }
            }' | {
            read -r dpath frag
            test -n "$dpath" || return

            # jq -r ".\"${dpath}\"" \
            #     <"${DEVDOCS_DIR}/${slug}/db.json" \
            #     >"${TEMP}/index.html"

            # screen -d -m http-server "${DEVDOCS_DIR}/${slug}/pages/" &
            screen -d -m npm run --prefix="$DEVDOCS_DIR" serve &

            sleep 0.35

            # $var = exec "$var"
            # lynx -assume_charset=utf-8 \
            $browser \
                "http://127.0.0.1:2517/${slug}/pages/${dpath}${frag}"
            # lynx -assume_charset=utf-8 \
            #     "file://localhost/${DEVDOCS_DIR}/${slug}/pages/${dpath}.html${frag}"

            # not using screen and will not
            pkill -9 screen
        }
    }
}

doc() {
    lr "$DEVDOCS_DIR" -1 -s -t 'type == d' -t '!type == d || depth > 0' -t 'name != "node_modules"' |
        doc_for "$(fzf --layout="reverse" --height=35% --prompt="Choose docs > ")"
        # doc_for "$(fzy -p 'Choose docs > ')"
}

purge() {
    lang=""
    dirs="$(lr "$DEVDOCS_DIR" -1 -s -t 'type == d' -t '!type == d || depth > 0' -t 'name != "node_modules"')"
    lang="$(echo "$dirs" | fzf --layout="reverse" --height=35% --prompt="Choose docs > " -0 -q "$@")"
    doc_dir="$DEVDOCS_DIR/$lang"
    [ ! -n "$lang" ] && exit 1
    echo "Selected '$lang' language"
    if [ -d "$doc_dir" ]; then
        gum confirm "Are you sure?" --default=false && rm -rf "$doc_dir" || echo "Cancelling"
    fi
}

print_help() {
    awk 'NR == 1 { next } /^$/ { exit } { print substr($0, 3) }' "$0" | sed "s#prog_name#$(basename "$0")#"
    exit 0
}

check_health() {
    echo "Missing programs:"
    __has awk      || echo "    awk"
    __has sed      || echo "    sed"
    __has fzf      || echo "    fzf"
    __has jq       || echo "    jq"
    __has lr       || echo "    lr"
    __has npm      || echo "    npm"
    __has node     || echo "    node"
    __has curl     || echo "    curl"
    __has screen   || echo "    screen"
    __has $browser || echo "    missing browser (lynx > w3m > elinks)"
}

main() {
    # shift program out?
    shift $((OPTIND - 1))

    trap '
        excode=$?; trap - EXIT;
        rm -rf '"$TEMP"'
        exit $excode
    ' INT TERM EXIT
    mkdir -p -m 700 "$TEMP"

    if [ $# -eq 0 ]; then
        doc
    elif [[ "$1" == "--help" || "$1" == "-h" || "$1" == "help" ]]; then
        print_help
    elif [[ "$1" == "--check" || "$1" == "-c" || "$1" == "check" ]]; then
        check_health
    elif [ "$1" = "get" ]; then
        shift
        get "$@ "
    # elif [ "$1" = "get_from" ]; then
    #     shift
    #     get_from "$@"
    # elif [ "$1" = "list" ]; then
    #     list
    elif [ "$1" = "regen" ]; then
        shift
        regen "$@ "
    elif [ "$1" = "purge" ]; then
        shift
        purge "$@ "
    elif [ "$1" = "reinit_cache_dir" ]; then
        init_cache_dir
    else
        while true; do
            doc_for "$@ " || exit 1
            sleep 1
        done
    fi
}

main "$@"

